server:
  port: 8087
spring:
  profiles:
    active: local
  application:
    name: kafka-long-running-jobs-microprocesses
  kafka:
    bootstrap-servers: localhost:29095
    consumer:
      auto-offset-reset: earliest
      group-id: kafka-long-running-jobs-spring-async
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
logging:
  level:
    root: INFO