server:
  port: 8086
spring:
  profiles:
    active: local
  application:
    name: kafka-long-running-jobs-not-async
  kafka:
    bootstrap-servers: localhost:29095
    consumer:
      auto-offset-reset: earliest
      group-id: kafka-long-running-jobs-not-async
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        max:
          poll:
            interval:
              ms: 300000 # Is the default. Set to 660000 (11 min) for this sample to work, since the thread.sleep is 10 min
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
logging:
  level:
    root: INFO