server:
  port: 8082
spring:
  profiles:
    active: local
  application:
    name: kafka-long-running-jobs-pause-container
  kafka:
    bootstrap-servers: localhost:29095
    consumer:
      auto-offset-reset: earliest
      group-id: kafka-long-running-jobs-pause-container
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
logging:
  level:
    root: INFO
kafka:
  container:
    id: "pause_container_id"